#include "vm.h"

enum {
  CLOCKS_TXT_BLANK_LEFT = 24,
  CLOCKS_TXT_BORDER_LEFT = 19,
  CLOCKS_TXT_ACTIVE = 240,

};

enum {
  VLINES_BLANK_TOP = 13,
  VLINES_BORDER_TOP = 27,
  VLINES_ACTIVE = SCREEN_HEIGHT,
  VLINES_BORDER_BOTTOM = 24,
  VLINES_BLANK_BOTTOM = 3,
  VLINES_VSYNC = 3,

  VLINES_TOTAL = VLINES_BLANK_TOP + VLINES_BORDER_TOP + VLINES_ACTIVE +
                 VLINES_BORDER_BOTTOM + VLINES_BLANK_BOTTOM + VLINES_VSYNC,
};
