#ifndef OPCODES_H
#define OPCODES_H

#include "abi.h"

enum {
  CPU_6502 = 1 << 0,
  CPU_6502X = 1 << 1,
  CPU_65C02 = 1 << 2,
};

static struct {
  char const *name;
  U8 cpu;
} const CPUS[] = {
    {"6502", CPU_6502},
    {"6502X", CPU_6502X},
    {"65C02", CPU_65C02},
};

enum {
  MNE_ADC,
  MNE_ALR,
  MNE_ANC,
  MNE_AND,
  MNE_ANE,
  MNE_ARR,
  MNE_ASL,
  MNE_BBR,
  MNE_BBS,
  MNE_BCC,
  MNE_BCS,
  MNE_BEQ,
  MNE_BIT,
  MNE_BMI,
  MNE_BNE,
  MNE_BPL,
  MNE_BRA,
  MNE_BRK,
  MNE_BVC,
  MNE_BVS,
  MNE_CLC,
  MNE_CLD,
  MNE_CLI,
  MNE_CLV,
  MNE_CMP,
  MNE_CPX,
  MNE_CPY,
  MNE_DCP,
  MNE_DEC,
  MNE_DEX,
  MNE_DEY,
  MNE_EOR,
  MNE_INC,
  MNE_INX,
  MNE_INY,
  MNE_ISC,
  MNE_JAM,
  MNE_JMP,
  MNE_JSR,
  MNE_LAS,
  MNE_LAX,
  MNE_LDA,
  MNE_LDX,
  MNE_LDY,
  MNE_LSR,
  MNE_LXA,
  MNE_NOP,
  MNE_ORA,
  MNE_PHA,
  MNE_PHP,
  MNE_PHX,
  MNE_PHY,
  MNE_PLA,
  MNE_PLP,
  MNE_PLX,
  MNE_PLY,
  MNE_RLA,
  MNE_RMB,
  MNE_ROL,
  MNE_ROR,
  MNE_RRA,
  MNE_RTI,
  MNE_RTS,
  MNE_SAX,
  MNE_SBC,
  MNE_SBX,
  MNE_SEC,
  MNE_SED,
  MNE_SEI,
  MNE_SHA,
  MNE_SHS,
  MNE_SHX,
  MNE_SHY,
  MNE_SLO,
  MNE_SMB,
  MNE_SRE,
  MNE_STA,
  MNE_STP,
  MNE_STX,
  MNE_STY,
  MNE_STZ,
  MNE_TAX,
  MNE_TAY,
  MNE_TRB,
  MNE_TSB,
  MNE_TSX,
  MNE_TXA,
  MNE_TXS,
  MNE_TYA,
  MNE_WAI,
};

enum {
  ADDR_IMP, // (implied)
  ADDR_IMM, // #$NN
  ADDR_ZPG, // $NN
  ADDR_ZPX, // $NN, X
  ADDR_ZPY, // $NN, Y
  ADDR_ABS, // $NNNN
  ADDR_ABX, // $NNNN, X
  ADDR_ABY, // $NNNN, Y
  ADDR_IND, // ($NNNN)
  ADDR_IZX, // ($NN, X)
  ADDR_IZY, // ($NN), Y
  ADDR_REL, // REL
  ADDR_IZP, // ($NN)
  ADDR_IAX, // ($NNNN, X)
  ADDR_BZP, // N, $NN
  ADDR_BZR, // N, $NN, REL
};

typedef struct {
  U8 op;
  U8 cpus; // 0 = this addressing mode does not exist
} Opcode;

typedef struct {
  char const *name;
  Opcode opcodes[16];
} Mnemonic;

#define OPCODE_ANY(op) {(op), CPU_6502 | CPU_6502X | CPU_65C02}
#define OPCODE_65C02(op) {(op), CPU_65C02}
#define OPCODE_6502X(op) {(op), CPU_6502X}

static Mnemonic const MNEMONICS[] = {
    [MNE_ADC] = {"ADC",
                 {[ADDR_IMM] = OPCODE_ANY(0x69),
                  [ADDR_ZPG] = OPCODE_ANY(0x65),
                  [ADDR_ZPX] = OPCODE_ANY(0x75),
                  [ADDR_ABS] = OPCODE_ANY(0x6D),
                  [ADDR_ABX] = OPCODE_ANY(0x7D),
                  [ADDR_ABY] = OPCODE_ANY(0x79),
                  [ADDR_IZX] = OPCODE_ANY(0x61),
                  [ADDR_IZY] = OPCODE_ANY(0x71),
                  [ADDR_IZP] = OPCODE_65C02(0x72)}},
    [MNE_ALR] = {"ALR", {[ADDR_IMM] = OPCODE_6502X(0x4B)}},
    [MNE_ANC] = {"ANC", {[ADDR_IMM] = OPCODE_6502X(0x0B)}},
    [MNE_AND] = {"AND",
                 {[ADDR_IMM] = OPCODE_ANY(0x29),
                  [ADDR_ZPG] = OPCODE_ANY(0x25),
                  [ADDR_ZPX] = OPCODE_ANY(0x35),
                  [ADDR_ABS] = OPCODE_ANY(0x2D),
                  [ADDR_ABX] = OPCODE_ANY(0x3D),
                  [ADDR_ABY] = OPCODE_ANY(0x39),
                  [ADDR_IZX] = OPCODE_ANY(0x21),
                  [ADDR_IZY] = OPCODE_ANY(0x31),
                  [ADDR_IZP] = OPCODE_65C02(0x32)}},
    [MNE_ANE] = {"ANE", {[ADDR_IMM] = OPCODE_6502X(0x8B)}},
    [MNE_ARR] = {"ARR", {[ADDR_IMM] = OPCODE_6502X(0x6B)}},
    [MNE_ASL] = {"ASL",
                 {[ADDR_IMP] = OPCODE_ANY(0x0A),
                  [ADDR_ZPG] = OPCODE_ANY(0x06),
                  [ADDR_ZPX] = OPCODE_ANY(0x16),
                  [ADDR_ABS] = OPCODE_ANY(0x0E),
                  [ADDR_ABX] = OPCODE_ANY(0x1E)}},
    [MNE_BBR] = {"BBR", {[ADDR_BZR] = OPCODE_65C02(0x0F)}},
    [MNE_BBS] = {"BBS", {[ADDR_BZR] = OPCODE_65C02(0x8F)}},
    [MNE_BCC] = {"BCC", {[ADDR_REL] = OPCODE_ANY(0x90)}},
    [MNE_BCS] = {"BCS", {[ADDR_REL] = OPCODE_ANY(0xB0)}},
    [MNE_BEQ] = {"BEQ", {[ADDR_REL] = OPCODE_ANY(0xF0)}},
    [MNE_BIT] = {"BIT",
                 {[ADDR_IMM] = OPCODE_65C02(0x89),
                  [ADDR_ZPG] = OPCODE_ANY(0x24),
                  [ADDR_ZPX] = OPCODE_65C02(0x34),
                  [ADDR_ABS] = OPCODE_ANY(0x2C),
                  [ADDR_ABX] = OPCODE_65C02(0x3C)}},
    [MNE_BMI] = {"BMI", {[ADDR_REL] = OPCODE_ANY(0x30)}},
    [MNE_BNE] = {"BNE", {[ADDR_REL] = OPCODE_ANY(0xD0)}},
    [MNE_BPL] = {"BPL", {[ADDR_REL] = OPCODE_ANY(0x10)}},
    [MNE_BRA] = {"BRA", {[ADDR_REL] = OPCODE_65C02(0x80)}},
    [MNE_BRK] = {"BRK", {[ADDR_IMM] = OPCODE_ANY(0x00)}},
    [MNE_BVC] = {"BVC", {[ADDR_REL] = OPCODE_ANY(0x50)}},
    [MNE_BVS] = {"BVS", {[ADDR_REL] = OPCODE_ANY(0x70)}},
    [MNE_CLC] = {"CLC", {[ADDR_IMP] = OPCODE_ANY(0x18)}},
    [MNE_CLD] = {"CLD", {[ADDR_IMP] = OPCODE_ANY(0xD8)}},
    [MNE_CLI] = {"CLI", {[ADDR_IMP] = OPCODE_ANY(0x58)}},
    [MNE_CLV] = {"CLV", {[ADDR_IMP] = OPCODE_ANY(0xB8)}},
    [MNE_CMP] = {"CMP",
                 {[ADDR_IMM] = OPCODE_ANY(0xC9),
                  [ADDR_ZPG] = OPCODE_ANY(0xC5),
                  [ADDR_ZPX] = OPCODE_ANY(0xD5),
                  [ADDR_ABS] = OPCODE_ANY(0xCD),
                  [ADDR_ABX] = OPCODE_ANY(0xDD),
                  [ADDR_ABY] = OPCODE_ANY(0xD9),
                  [ADDR_IZX] = OPCODE_ANY(0xC1),
                  [ADDR_IZY] = OPCODE_ANY(0xD1),
                  [ADDR_IZP] = OPCODE_65C02(0xD2)}},
    [MNE_CPX] = {"CPX",
                 {[ADDR_IMM] = OPCODE_ANY(0xE0),
                  [ADDR_ZPG] = OPCODE_ANY(0xE4),
                  [ADDR_ABS] = OPCODE_ANY(0xEC)}},
    [MNE_CPY] = {"CPY",
                 {[ADDR_IMM] = OPCODE_ANY(0xC0),
                  [ADDR_ZPG] = OPCODE_ANY(0xC4),
                  [ADDR_ABS] = OPCODE_ANY(0xCC)}},
    [MNE_DCP] = {"DCP",
                 {[ADDR_ZPG] = OPCODE_6502X(0xC7),
                  [ADDR_ZPX] = OPCODE_6502X(0xD7),
                  [ADDR_ABS] = OPCODE_6502X(0xCF),
                  [ADDR_ABX] = OPCODE_6502X(0xDF),
                  [ADDR_ABY] = OPCODE_6502X(0xDB),
                  [ADDR_IZX] = OPCODE_6502X(0xC3),
                  [ADDR_IZY] = OPCODE_6502X(0xD3)}},
    [MNE_DEC] = {"DEC",
                 {[ADDR_IMP] = OPCODE_65C02(0x3A),
                  [ADDR_ZPG] = OPCODE_ANY(0xC6),
                  [ADDR_ZPX] = OPCODE_ANY(0xD6),
                  [ADDR_ABS] = OPCODE_ANY(0xCE),
                  [ADDR_ABX] = OPCODE_ANY(0xDE)}},
    [MNE_DEX] = {"DEX", {[ADDR_IMP] = OPCODE_ANY(0xCA)}},
    [MNE_DEY] = {"DEY", {[ADDR_IMP] = OPCODE_ANY(0x88)}},
    [MNE_EOR] = {"EOR",
                 {[ADDR_IMM] = OPCODE_ANY(0x49),
                  [ADDR_ZPG] = OPCODE_ANY(0x45),
                  [ADDR_ZPX] = OPCODE_ANY(0x55),
                  [ADDR_ABS] = OPCODE_ANY(0x4D),
                  [ADDR_ABX] = OPCODE_ANY(0x5D),
                  [ADDR_ABY] = OPCODE_ANY(0x59),
                  [ADDR_IZX] = OPCODE_ANY(0x41),
                  [ADDR_IZY] = OPCODE_ANY(0x51),
                  [ADDR_IZP] = OPCODE_65C02(0x52)}},
    [MNE_INC] = {"INC",
                 {[ADDR_IMP] = OPCODE_65C02(0x1A),
                  [ADDR_ZPG] = OPCODE_ANY(0xE6),
                  [ADDR_ZPX] = OPCODE_ANY(0xF6),
                  [ADDR_ABS] = OPCODE_ANY(0xEE),
                  [ADDR_ABX] = OPCODE_ANY(0xFE)}},
    [MNE_INX] = {"INX", {[ADDR_IMP] = OPCODE_ANY(0xE8)}},
    [MNE_INY] = {"INY", {[ADDR_IMP] = OPCODE_ANY(0xC8)}},
    [MNE_ISC] = {"ISC",
                 {[ADDR_ZPG] = OPCODE_6502X(0xE7),
                  [ADDR_ZPX] = OPCODE_6502X(0xF7),
                  [ADDR_ABS] = OPCODE_6502X(0xEF),
                  [ADDR_ABX] = OPCODE_6502X(0xFF),
                  [ADDR_ABY] = OPCODE_6502X(0xFB),
                  [ADDR_IZX] = OPCODE_6502X(0xE3),
                  [ADDR_IZY] = OPCODE_6502X(0xF3)}},
    [MNE_JAM] = {"JAM", {[ADDR_IMP] = OPCODE_6502X(0x02)}},
    [MNE_JMP] = {"JMP",
                 {[ADDR_ABS] = OPCODE_ANY(0x4C),
                  [ADDR_IND] = OPCODE_ANY(0x6C),
                  [ADDR_IAX] = OPCODE_65C02(0x7C)}},
    [MNE_JSR] = {"JSR", {[ADDR_ABS] = OPCODE_ANY(0x20)}},
    [MNE_LAS] = {"LAS", {[ADDR_ABY] = OPCODE_6502X(0xBB)}},
    [MNE_LAX] = {"LAX",
                 {[ADDR_ZPG] = OPCODE_6502X(0xA7),
                  [ADDR_ZPY] = OPCODE_6502X(0xB7),
                  [ADDR_ABS] = OPCODE_6502X(0xAF),
                  [ADDR_ABY] = OPCODE_6502X(0xBF),
                  [ADDR_IZX] = OPCODE_6502X(0xA3),
                  [ADDR_IZY] = OPCODE_6502X(0xB3)}},
    [MNE_LDA] = {"LDA",
                 {[ADDR_IMM] = OPCODE_ANY(0xA9),
                  [ADDR_ZPG] = OPCODE_ANY(0xA5),
                  [ADDR_ZPX] = OPCODE_ANY(0xB5),
                  [ADDR_ABS] = OPCODE_ANY(0xAD),
                  [ADDR_ABX] = OPCODE_ANY(0xBD),
                  [ADDR_ABY] = OPCODE_ANY(0xB9),
                  [ADDR_IZX] = OPCODE_ANY(0xA1),
                  [ADDR_IZY] = OPCODE_ANY(0xB1),
                  [ADDR_IZP] = OPCODE_65C02(0xB2)}},
    [MNE_LDX] = {"LDX",
                 {[ADDR_IMM] = OPCODE_ANY(0xA2),
                  [ADDR_ZPG] = OPCODE_ANY(0xA6),
                  [ADDR_ZPY] = OPCODE_ANY(0xB6),
                  [ADDR_ABS] = OPCODE_ANY(0xAE),
                  [ADDR_ABY] = OPCODE_ANY(0xBE)}},
    [MNE_LDY] = {"LDY",
                 {[ADDR_IMM] = OPCODE_ANY(0xA0),
                  [ADDR_ZPG] = OPCODE_ANY(0xA4),
                  [ADDR_ZPX] = OPCODE_ANY(0xB4),
                  [ADDR_ABS] = OPCODE_ANY(0xAC),
                  [ADDR_ABX] = OPCODE_ANY(0xBC)}},
    [MNE_LSR] = {"LSR",
                 {[ADDR_IMP] = OPCODE_ANY(0x4A),
                  [ADDR_ZPG] = OPCODE_ANY(0x46),
                  [ADDR_ZPX] = OPCODE_ANY(0x56),
                  [ADDR_ABS] = OPCODE_ANY(0x4E),
                  [ADDR_ABX] = OPCODE_ANY(0x5E)}},
    [MNE_LXA] = {"LXA", {[ADDR_IMM] = OPCODE_6502X(0xAB)}},
    [MNE_NOP] = {"NOP",
                 {[ADDR_IMP] = OPCODE_ANY(0xEA),
                  [ADDR_IMM] = OPCODE_6502X(0x80),
                  [ADDR_ZPG] = OPCODE_6502X(0x04),
                  [ADDR_ZPX] = OPCODE_6502X(0x14),
                  [ADDR_ABS] = OPCODE_6502X(0x0C),
                  [ADDR_ABX] = OPCODE_6502X(0x1C)}},
    [MNE_ORA] = {"ORA",
                 {[ADDR_IMM] = OPCODE_ANY(0x09),
                  [ADDR_ZPG] = OPCODE_ANY(0x05),
                  [ADDR_ZPX] = OPCODE_ANY(0x15),
                  [ADDR_ABS] = OPCODE_ANY(0x0D),
                  [ADDR_ABX] = OPCODE_ANY(0x1D),
                  [ADDR_ABY] = OPCODE_ANY(0x19),
                  [ADDR_IZX] = OPCODE_ANY(0x01),
                  [ADDR_IZY] = OPCODE_ANY(0x11),
                  [ADDR_IZP] = OPCODE_65C02(0x12)}},
    [MNE_PHA] = {"PHA", {[ADDR_IMP] = OPCODE_ANY(0x48)}},
    [MNE_PHP] = {"PHP", {[ADDR_IMP] = OPCODE_ANY(0x08)}},
    [MNE_PHX] = {"PHX", {[ADDR_IMP] = OPCODE_65C02(0xDA)}},
    [MNE_PHY] = {"PHY", {[ADDR_IMP] = OPCODE_65C02(0x5A)}},
    [MNE_PLA] = {"PLA", {[ADDR_IMP] = OPCODE_ANY(0x68)}},
    [MNE_PLP] = {"PLP", {[ADDR_IMP] = OPCODE_ANY(0x28)}},
    [MNE_PLX] = {"PLX", {[ADDR_IMP] = OPCODE_65C02(0xFA)}},
    [MNE_PLY] = {"PLY", {[ADDR_IMP] = OPCODE_65C02(0x7A)}},
    [MNE_RLA] = {"RLA",
                 {[ADDR_ZPG] = OPCODE_6502X(0x27),
                  [ADDR_ZPX] = OPCODE_6502X(0x37),
                  [ADDR_ABS] = OPCODE_6502X(0x2F),
                  [ADDR_ABX] = OPCODE_6502X(0x3F),
                  [ADDR_ABY] = OPCODE_6502X(0x3B),
                  [ADDR_IZX] = OPCODE_6502X(0x23),
                  [ADDR_IZY] = OPCODE_6502X(0x33)}},
    [MNE_RMB] = {"RMB", {[ADDR_BZP] = OPCODE_65C02(0x07)}},
    [MNE_ROL] = {"ROL",
                 {[ADDR_IMP] = OPCODE_ANY(0x2A),
                  [ADDR_ZPG] = OPCODE_ANY(0x26),
                  [ADDR_ZPX] = OPCODE_ANY(0x36),
                  [ADDR_ABS] = OPCODE_ANY(0x2E),
                  [ADDR_ABX] = OPCODE_ANY(0x3E)}},
    [MNE_ROR] = {"ROR",
                 {[ADDR_IMP] = OPCODE_ANY(0x6A),
                  [ADDR_ZPG] = OPCODE_ANY(0x66),
                  [ADDR_ZPX] = OPCODE_ANY(0x76),
                  [ADDR_ABS] = OPCODE_ANY(0x6E),
                  [ADDR_ABX] = OPCODE_ANY(0x7E)}},
    [MNE_RRA] = {"RRA",
                 {[ADDR_ZPG] = OPCODE_6502X(0x67),
                  [ADDR_ZPX] = OPCODE_6502X(0x77),
                  [ADDR_ABS] = OPCODE_6502X(0x6F),
                  [ADDR_ABX] = OPCODE_6502X(0x7F),
                  [ADDR_ABY] = OPCODE_6502X(0x7B),
                  [ADDR_IZX] = OPCODE_6502X(0x63),
                  [ADDR_IZY] = OPCODE_6502X(0x73)}},
    [MNE_RTI] = {"RTI", {[ADDR_IMP] = OPCODE_ANY(0x40)}},
    [MNE_RTS] = {"RTS", {[ADDR_IMP] = OPCODE_ANY(0x60)}},
    [MNE_SAX] = {"SAX",
                 {[ADDR_ZPG] = OPCODE_6502X(0x87),
                  [ADDR_ZPY] = OPCODE_6502X(0x97),
                  [ADDR_ABS] = OPCODE_6502X(0x8F),
                  [ADDR_IZX] = OPCODE_6502X(0x83)}},
    [MNE_SBC] = {"SBC",
                 {[ADDR_IMM] = OPCODE_ANY(0xE9),
                  [ADDR_ZPG] = OPCODE_ANY(0xE5),
                  [ADDR_ZPX] = OPCODE_ANY(0xF5),
                  [ADDR_ABS] = OPCODE_ANY(0xED),
                  [ADDR_ABX] = OPCODE_ANY(0xFD),
                  [ADDR_ABY] = OPCODE_ANY(0xF9),
                  [ADDR_IZX] = OPCODE_ANY(0xE1),
                  [ADDR_IZY] = OPCODE_ANY(0xF1),
                  [ADDR_IZP] = OPCODE_65C02(0xF2)}},
    [MNE_SBX] = {"SBX", {[ADDR_IMM] = OPCODE_6502X(0xCB)}},
    [MNE_SEC] = {"SEC", {[ADDR_IMP] = OPCODE_ANY(0x38)}},
    [MNE_SED] = {"SED", {[ADDR_IMP] = OPCODE_ANY(0xF8)}},
    [MNE_SEI] = {"SEI", {[ADDR_IMP] = OPCODE_ANY(0x78)}},
    [MNE_SHA] =
        {"SHA",
         {[ADDR_ABY] = OPCODE_6502X(0x9F), [ADDR_IZY] = OPCODE_6502X(0x93)}},
    [MNE_SHS] = {"SHS", {[ADDR_ABY] = OPCODE_6502X(0x9B)}},
    [MNE_SHX] = {"SHX", {[ADDR_ABY] = OPCODE_6502X(0x9E)}},
    [MNE_SHY] = {"SHY", {[ADDR_ABX] = OPCODE_6502X(0x9C)}},
    [MNE_SLO] = {"SLO",
                 {[ADDR_ZPG] = OPCODE_6502X(0x07),
                  [ADDR_ZPX] = OPCODE_6502X(0x17),
                  [ADDR_ABS] = OPCODE_6502X(0x0F),
                  [ADDR_ABX] = OPCODE_6502X(0x1F),
                  [ADDR_ABY] = OPCODE_6502X(0x1B),
                  [ADDR_IZX] = OPCODE_6502X(0x03),
                  [ADDR_IZY] = OPCODE_6502X(0x13)}},
    [MNE_SMB] = {"SMB", {[ADDR_BZP] = OPCODE_65C02(0x87)}},
    [MNE_SRE] = {"SRE",
                 {[ADDR_ZPG] = OPCODE_6502X(0x47),
                  [ADDR_ZPX] = OPCODE_6502X(0x57),
                  [ADDR_ABS] = OPCODE_6502X(0x4F),
                  [ADDR_ABX] = OPCODE_6502X(0x5F),
                  [ADDR_ABY] = OPCODE_6502X(0x5B),
                  [ADDR_IZX] = OPCODE_6502X(0x43),
                  [ADDR_IZY] = OPCODE_6502X(0x53)}},
    [MNE_STA] = {"STA",
                 {[ADDR_ZPG] = OPCODE_ANY(0x85),
                  [ADDR_ZPX] = OPCODE_ANY(0x95),
                  [ADDR_ABS] = OPCODE_ANY(0x8D),
                  [ADDR_ABX] = OPCODE_ANY(0x9D),
                  [ADDR_ABY] = OPCODE_ANY(0x99),
                  [ADDR_IZX] = OPCODE_ANY(0x81),
                  [ADDR_IZY] = OPCODE_ANY(0x91),
                  [ADDR_IZP] = OPCODE_65C02(0x92)}},
    [MNE_STP] = {"STP", {[ADDR_IMP] = OPCODE_65C02(0xDB)}},
    [MNE_STX] = {"STX",
                 {[ADDR_ZPG] = OPCODE_ANY(0x86),
                  [ADDR_ZPY] = OPCODE_ANY(0x96),
                  [ADDR_ABS] = OPCODE_ANY(0x8E)}},
    [MNE_STY] = {"STY",
                 {[ADDR_ZPG] = OPCODE_ANY(0x84),
                  [ADDR_ZPX] = OPCODE_ANY(0x94),
                  [ADDR_ABS] = OPCODE_ANY(0x8C)}},
    [MNE_STZ] = {"STZ",
                 {[ADDR_ZPG] = OPCODE_65C02(0x64),
                  [ADDR_ZPX] = OPCODE_65C02(0x74),
                  [ADDR_ABS] = OPCODE_65C02(0x9C),
                  [ADDR_ABX] = OPCODE_65C02(0x9E)}},
    [MNE_TAX] = {"TAX", {[ADDR_IMP] = OPCODE_ANY(0xAA)}},
    [MNE_TAY] = {"TAY", {[ADDR_IMP] = OPCODE_ANY(0xA8)}},
    [MNE_TRB] =
        {"TRB",
         {[ADDR_ZPG] = OPCODE_65C02(0x14), [ADDR_ABS] = OPCODE_65C02(0x1C)}},
    [MNE_TSB] =
        {"TSB",
         {[ADDR_ZPG] = OPCODE_65C02(0x04), [ADDR_ABS] = OPCODE_65C02(0x0C)}},
    [MNE_TSX] = {"TSX", {[ADDR_IMP] = OPCODE_ANY(0xBA)}},
    [MNE_TXA] = {"TXA", {[ADDR_IMP] = OPCODE_ANY(0x8A)}},
    [MNE_TXS] = {"TXS", {[ADDR_IMP] = OPCODE_ANY(0x9A)}},
    [MNE_TYA] = {"TYA", {[ADDR_IMP] = OPCODE_ANY(0x98)}},
    [MNE_WAI] = {"WAI", {[ADDR_IMP] = OPCODE_65C02(0xCB)}},
};

#endif // OPCODES_H
